name = "amazon-d0v2"
main = "src/worker.ts"
compatibility_date = "2026-09-11"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"
not_found_handling = "single-page-application"
